# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Project-12-MusicSearchApp' do

pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

pod 'MONActivityIndicatorView'

end

target 'Project-12-MusicSearchAppTests' do

end

