# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Project-11-Swifter' do

# Alert
pod 'SIAlertView'

end

target 'Project-11-SwifterTests' do

end

