# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Project-8-JustDoIt' do
    # Font
    pod 'LatoFont', :git => "https://github.com/gscalzo/LatoFont.git"
    # Swipe Table View Cells
    pod 'MGSwipeTableCell', '~> 1.5.1'

end

