# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!
 inhibit_all_warnings!

target 'Project-9-FlappyTurd' do

    # Auto layout in code
    pod 'Cartography', :git => "https://github.com/robb/Cartography.git", :tag => '0.6.0'

    # Custom Button
    pod 'HTPressableButton', '~> 1.3.2'

end

